### ISSUE TITLE
Apache + mod_wsgi on CentOS7 gives HTTP/500 with default config

### ISSUE THREAD

**Issue by seitzbg** [PowerDNS/pdnscontrol#107]
pdnscontrol.conf:

DEBUG = False I get:

```
10.119.134.34 - - [07/Apr/2015:17:49:41 +0000] "GET /pdnscontrol/auth/login?next=%2Fpdnscontrol%2F HTTP/1.1" 500 291 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0"
```

```
[Tue Apr 07 17:51:53.566309 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196] mod_wsgi (pid=13550): Exception occurred processing WSGI script '/opt/pdnscontrol/instance/pdnscontrol.wsgi'.
[Tue Apr 07 17:51:53.566392 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196] Traceback (most recent call last):
[Tue Apr 07 17:51:53.566434 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
[Tue Apr 07 17:51:53.566493 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     return self.wsgi_app(environ, start_response)
[Tue Apr 07 17:51:53.566577 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
[Tue Apr 07 17:51:53.566628 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     response = self.make_response(self.handle_exception(e))
[Tue Apr 07 17:51:53.566654 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
[Tue Apr 07 17:51:53.566688 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     reraise(exc_type, exc_value, tb)
[Tue Apr 07 17:51:53.566734 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Tue Apr 07 17:51:53.566775 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     response = self.full_dispatch_request()
[Tue Apr 07 17:51:53.566799 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Tue Apr 07 17:51:53.566832 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     rv = self.handle_user_exception(e)
[Tue Apr 07 17:51:53.566855 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Tue Apr 07 17:51:53.566887 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     reraise(exc_type, exc_value, tb)
[Tue Apr 07 17:51:53.566909 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Tue Apr 07 17:51:53.566975 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     rv = self.dispatch_request()
[Tue Apr 07 17:51:53.567001 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Tue Apr 07 17:51:53.567035 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Apr 07 17:51:53.567060 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask_security/decorators.py", line 205, in wrapper
[Tue Apr 07 17:51:53.567096 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     return f(*args, **kwargs)
[Tue Apr 07 17:51:53.567120 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask_security/views.py", line 87, in login
[Tue Apr 07 17:51:53.567155 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     **_ctx('login'))
[Tue Apr 07 17:51:53.567178 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask_security/core.py", line 439, in render_template
[Tue Apr 07 17:51:53.567212 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     return render_template(*args, **kwargs)
[Tue Apr 07 17:51:53.567235 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
[Tue Apr 07 17:51:53.567268 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     context, ctx.app)
[Tue Apr 07 17:51:53.567291 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
[Tue Apr 07 17:51:53.567324 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     rv = template.render(context)
[Tue Apr 07 17:51:53.567346 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
[Tue Apr 07 17:51:53.567381 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     return self.environment.handle_exception(exc_info, True)
[Tue Apr 07 17:51:53.567404 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
[Tue Apr 07 17:51:53.567437 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     reraise(exc_type, exc_value, tb)
[Tue Apr 07 17:51:53.567460 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/pdnscontrol/templates/security/login_user.html", line 2, in top-level template code
[Tue Apr 07 17:51:53.567493 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     {% from "security/_macros.html" import render_field_with_errors, render_field %}
[Tue Apr 07 17:51:53.567550 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/pdnscontrol/templates/layout.html", line 8, in top-level template code
[Tue Apr 07 17:51:53.567592 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     {% assets "styles" %}
[Tue Apr 07 17:51:53.567616 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 181, in _render_assets
[Tue Apr 07 17:51:53.567652 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     urls = bundle.urls(env=env)
[Tue Apr 07 17:51:53.567675 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/webassets/bundle.py", line 681, in urls
[Tue Apr 07 17:51:53.567768 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     urls.extend(bundle._urls(env, extra_filters, *args, **kwargs))
[Tue Apr 07 17:51:53.567795 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/webassets/bundle.py", line 644, in _urls
[Tue Apr 07 17:51:53.567828 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     return [self._make_output_url(env)]
[Tue Apr 07 17:51:53.567849 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/webassets/bundle.py", line 601, in _make_output_url
[Tue Apr 07 17:51:53.567879 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     version = self.get_version(env, refresh=env.auto_build)
[Tue Apr 07 17:51:53.567901 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]   File "/opt/pdnscontrol/lib/python2.7/site-packages/webassets/bundle.py", line 227, in get_version
[Tue Apr 07 17:51:53.567931 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196]     'determined dynamically, because: %s') % (self, reason))
[Tue Apr 07 17:51:53.567973 2015] [:error] [pid 13550:tid 139980749518592] [remote 10.119.134.34:196] BundleError: Cannot find version of <Bundle output=gen/styles-%(version)s.css, filters=(), contents=('stylesheets/app.css',)>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
```

DEBUG = True works.

**Comment by seitzbg** [comment]
Also if a user enables Debug in the .conf, could you make the WSGI portion enable debug as well?

application.debug = True

**Comment by seitzbg** [comment]
I was missing this part:

bin/python manage.py assets --parse-templates build
