### ISSUE TITLE
Bug in install.py / flask_security

### ISSUE THREAD

**Issue by gerdnb** [PowerDNS/pdnscontrol#91]
(venv-pdnscontrol)root@server:/virtualenvs/venv-pdnscontrol/pdnscontrol# python install.py
The database has been created.
type:<type 'str'>
Traceback (most recent call last):
  File "install.py", line 30, in <module>
    admin = user_datastore.create_user(email=admin_email, name=u'The Admin', password=encrypt_password(admin_password))
  File "/virtualenvs/venv-pdnscontrol/local/lib/python2.7/site-packages/flask_security/utils.py", line 141, in encrypt_password
    signed = get_hmac(password).decode('ascii')
  File "/virtualenvs/venv-pdnscontrol/local/lib/python2.7/site-packages/flask_security/utils.py", line 104, in get_hmac
    h = hmac.new(_security.password_salt.encode('utf-8'), password.encode('utf-8'), hashlib.sha512)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1: ordinal not in range(128)

**Comment by zeha** [comment]
I've updated the Flask-Security and Flask-Login versions, and can no longer reproduce this issue.
