### ISSUE TITLE
UnicodeDecodeError on python install.py

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdnscontrol#95]
```
python install.py
The database has been created.
Traceback (most recent call last):
  File "install.py", line 27, in <module>
    admin = user_datastore.create_user(email=admin_email, name=u'The Admin', password=encrypt_password(admin_password))
  File "/home/jpm/pdnscontrol/venv-pdnscontrol/local/lib/python2.7/site-packages/flask_security/utils.py", line 141, in encrypt_password
    signed = get_hmac(password).decode('ascii')
  File "/home/jpm/pdnscontrol/venv-pdnscontrol/local/lib/python2.7/site-packages/flask_security/utils.py", line 104, in get_hmac
    h = hmac.new(_security.password_salt.encode('utf-8'), password.encode('utf-8'), hashlib.sha512)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdc in position 7: ordinal not in range(128)
```

Tables are created but are all empty.

instance/pdnscontrol.conf:

```
SECRET_KEY = '\x8b\x1b\nqz0\x92X<w\xb1/1\xdf\xcf\xc2\xa2\xf6\x9c\xe0y\xaa\x19\xa0\x1a\x06\xe9\xc5\xf9\xd2\x12HT_\xa4\x11\xf53l\xb7\x19\x0e'
SECURITY_PASSWORD_SALT = '**aqqL\x17\xdc\xfe\x7f(5Ds\x8dR'
```

created as suggested in the .conf.

**Comment by jpmens** [comment]
```
The database has been created.
Traceback (most recent call last):
  File "install.py", line 28, in <module>
    admin = user_datastore.create_user(email=admin_email, name=u'The Admin', password=encrypt_password(admin_password))
  File "/home/jpm/pdnscontrol/venv-pdnscontrol/local/lib/python2.7/site-packages/flask_security/utils.py", line 141, in encrypt_password
    signed = get_hmac(password).decode('ascii')
  File "/home/jpm/pdnscontrol/venv-pdnscontrol/local/lib/python2.7/site-packages/flask_security/utils.py", line 104, in get_hmac
    h = hmac.new(_security.password_salt.encode('utf-8'), password.encode('utf-8'), hashlib.sha512)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdc in position 7: ordinal not in range(128)
```

**Comment by jpmens** [comment]
works after `pip install -r requirements.txt`; thanks.
